# sklearn.preprocessing.LabelEncoder

> class sklearn.preprocessing.LabelEncoder

### Attributes
- classes_ : ndarray of shape (n_classes,)

### Methods
- fit(y)
    - Fit label encoder.

- fit_transform(y)
    - Fit label encoder and return encoded labels.

- get_params([deep])
    - Get parameters for this estimator.

- inverse_transform(y)
    - Transform labels back to original encoding.

- set_output(*[, transform])
    - Set output container.

- set_params(**params)
    - Set the parameters of this estimator.

- transform(y)
    - Transform labels to normalized encoding.

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit() & transform()으로 label 인코딩 수행.

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [4]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


# sklearn.preprocessing.OneHotEncoder

> class sklearn.preprocessing.OneHotEncoder(*, categories=‘auto’, drop=None, sparse=‘deprecated’, sparse_output=True, dtype=<class ‘numpy.float64’>, handle_unknown=‘error’, min_frequency=None, max_categories=None)

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [6]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1, 1)

# one-hot encoding 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)



원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [12]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환

# encoder.fit(items)
# labels = encoder.transform(items)

# 2차원 데이터로 변환
# labels = labels.reshape(-1, 1)
# items_ = encoder.transform(items)
# items_ = items_.reshape(-1,1)

# one-hot encoding 적용
data = np.array(items).reshape(-1, 1)
ohe = OneHotEncoder()
data

# result = ohe.fit_transform(data)



array([['TV'],
       ['냉장고'],
       ['전자렌지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U4')

In [13]:
import pandas as pd


In [15]:
df =pd.DataFrame({'item' : ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)


item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

# Data Scaling

> data 표준 및 정규화 

## sklearn의 Scaler

1. StandardScaler -> 표준화

2. MinMaxScaler -> 정규화

In [16]:
from sklearn.datasets import load_iris
import pandas as pd

In [18]:
# 붓꽃 데이터 셋 로딩 -> df 변환

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data= iris_data, columns= iris.feature_names)
# iris_df

print('feature들의 평균')
print(iris_df.mean())
print('\nfeature들의 분산 값')
print(iris_df.var())



feature들의 평균
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
# 표준화후 mean & variance 재확인

# StandardScaler객체생성
scaler = StandardScaler()

# StandardScaler 로 데이터 셋 변환. fit() 과 transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시, scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print('mean of features')
print(iris_df_scaled.mean())
print('\n variance of features')
print(iris_df_scaled.var())

mean of features
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

 variance of features
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [22]:
# MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

# iris 다시 로드
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data= iris_data, columns= iris.feature_names)

# MinMax 객체생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 셋 변환. fit() & transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시, scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print('feature들의 최소값')
print(iris_df_scaled.min())
print('\nfeature들의 최대값')
print(iris_df_scaled.max())

feature들의 최소값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
